//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musteri.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public satis()
        {
            this.satisDetay = new HashSet<satisDetay>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string adSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satisDetay> satisDetay { get; set; }
    }
}
